export const fourStatements = [{
    title: 'Military’s very first statement about the election',
    subtitle: 'Statement on Stance, November 30, 2020',
    description: 'The Union Election Commission is an “organization formed by the President in accord with the provisions on appointment of the Union Ministers prescribed in this Constitution mentioned in Sub-section (a) of Section 398 of the Constitution (2008) of the Republic of the Union of Myanmar and the organization which shall make final and conclusive resolutions on election functions, appeals and revisions relating to the resolutions and orders of the election tribunals and matters taken under the law relating to political party in accord with Section 402 of the Constitution”. As Union Ministers shall be responsible to the President in accord with Sub-section (h) of the Section 232, it is considered that the Union Election Commission formed in accord with these provision should also be responsible to the President. As such, the President should necessarily supervise and control functions of the Union Election Commission to be legal, righteous, justice and fair.\n' +
        '\n' +
        'It was learnt that electoral disputes in the general election held on 8 November 2020 occurred across the nation. The Tatmadaw is scrutinizing and reviewing the election processes in 218 townships where servicemen from regiments and units of the Tatmadaw and their family members cast votes whether election processes happened in accord with the law or not. Depending on findings of the scrutiny and reviews, voters from respective constituencies will submit electoral objections to the Union Election Commission if necessary. As it is efforts to recognize a free and fair election without suspicion, the request was made to the Union Election Commission for giving necessary directives to respective election sub-commissions to be able to allow copying of public documents in accord with Section 74 and Section 76 of the Evidence Act when permission is sought for copying necessary documents which need in scrutinizing and reviewing the election processes.\n' +
        '\n' +
        'The Statement on Stance was released that the Tatmadaw will scrutinize the townships where servicemen of regiments and units of the Tatmadaw and their family members cast votes with the aim of enabling the people to recognize the election to be free and fair without suspicion and further straightening the Myanmar political path in the future with essence of democracy such as good practices of abiding by the law.\n'
}, {
    title: 'Military response to UEC statement',
    subtitle: 'The Statement in connection with the attitude towards the statement issued by Union Election Commission',
    description: '1. The Union Election Commission (UEC) issued a statement in connection with the instructions in accordance with Sections 74 and 76 of the Evidence Act on 7 December 2020. The paragraph (1) of the announcement refers to the Statement issued by the Tatmadaw Information Team on 30 November.\n' +
        '\n' +
        '2. As regards the paragraph (2) which says that in giving reasons for submitting objection of voters from military units, permits are being asked to copy the relevant documents in referring to the sections 74 and 76 of Evidence Act, it is obvious that the Evidence Act applies to all judicial proceedings in or before any Court.  As the disputes may occur whether the Election Tribunal is a court or not, the Section 78 of the respective Hluttaw Election Laws, which states, “In examining the electoral objections, the Election Tribunal has the right to apply the provisions of the Evidence Act” vests the Election Tribunal with the right to exercise the Evidence Act.  Hence, the provisions of the Evidence Act are related to the case of examining the electoral objections by the Election Tribunal.\n' +
        '\n' +
        '3. According to the Section 77 of the respective Hluttaw Election Laws, the case of examining the  objections by the Election Tribunal shall be deemed as a judicial process. The Section 77 of the respective Hluttaw Election Laws states, “The Election Tribunal has the right to exercise the powers vested in the Court under the Code of Civil Procedure. In addition, it may, on its own motion summon and examine any person who is considered to be able to produce material evidence.”\n' +
        '\n' +
        '4. Moreover, Rule 88b of the respective Hluttaw Election Rules states that an objector shall provide a brief account of the important evidences in the letter of objection; that if necessary he/she shall number the paragraphs of the objection, and that the verification of objections shall be signed by the objector in accordance with the provisions of the Code of Civil Procedure relating to verification of pleadings. The Rule 94 of the Rules also states that without contrary to the provisions of the Rules the Election Tribunal shall examine as civil cases in accordance with the procedures of the Code of Civil Procedure. According to the Rules, the Election Tribunal shall be deemed as a judicial process.\n' +
        '\n' +
        '5. In the Evidence Act, documentary evidence means “all documents produced for the inspection of the Court; such documents are called documentary evidence”. Hence, the act of demanding the permission to copy the documents to be presented to the Election Tribunal, which has the right to apply the Evidence Act and the Code of Civil Procedure, for hearing the case in respect of election objections and which shall be deemed as a judicial process, is legally appropriate.\n' +
        '\n' +
        '6. As regards the paragraph (3) the Northern Command asked the permission to copy the documents under the rights of the concerned voters. The election sub-commissions at different levels also have the right to permit the duplication of the ones that can be allowed and to deny the request with firm reason.\n' +
        '\n' +
        '7. The paragraph (4) says that “the Hluttaw Election Laws and Rules do not stipulate that requests for a copy of election document shall be allowed.” According to provisions in respect of the electoral malpractices and the filling of electoral objections, the said statement does not encompass the entire respective Hluttaw Election Laws. As the electoral objections shall be examined in accordance with the Code of Civil Procedure and the Election Tribunal has been empowered with the right to exercise the Evidence Act, Sections 74 and 76 of the Evidence Act become inclusive in the event of electoral objections in respect of the electoral malpractices surface.\n' +
        '\n' +
        '8. In the paragraph (5), it is stated that “Section 78 of the election laws provided for that only when examining the electoral objections, the Election Tribunal has the right to apply the provisions of the Evidence Act.” In this statement, the expression “in examining the electoral objections” of the original provision, which stipulates, “In examining the electoral objections, the Election Tribunal has the right to apply the provisions of the Evidence Act” is substituted with the expression “only when examining the electoral objections”. It is found that this substitution has ruined the essence of the original provision. Faithfulness is of vital importance in referring a provision of a law. It must be aware that the addition of the word “only when” can change the essence and definition of the original provision a lot.\n' +
        '\n' +
        '9. The paragraph (5) also states “The Election Tribunal of the Union Election Commission has the right to apply the provisions of the Evidence Act only when examining the electoral objections. It does not define ‘must apply’”. In fact, the Section 78 is not a provision that says that Evidence Act may be applied. It is a provision that entrusts the Election Tribunal with the right to apply the Evidence Act. The expression “It does not define ‘must apply’” can be deemed a wrong interpretation of the expression “has the right to apply”. So, it can be remarked as a wrong interpretation in terms of law.\n' +
        '\n' +
        '10.    In the paragraph (6), it is stated, “the Union Election Commission has refused to issue unlawful directives to the respective election sub-commissions as requested by the Tatmadaw Information Team.” Whatever attitude the UEC has, the request to copy the documents on the electoral objections, the Election Tribunal whose nature of work is concerned with court hearing and which has the right to apply Evidence Act and the Code of Civil Procedure, is going to examine, is made in accordance with the legal right of a citizen to vote and file an objection. So, it doesn’t amount to issuing an unlawful directive.\n' +
        '\n' +
        '11.    There are two principles under the natural justice or in other words the duty to act fairly. The first principle is “against bias” or “Nemo judex in causa sua” in Latin legal term. The second principle is “the right to fair hearing” or “Audi alteram partem” in Latin legal term. Hence, the Union Election Commission should work towards removing all the doubts through transparency, purity and fairness based on the natural justice.\n'
}, {
    title: "Such law must be revoked",
    subtitle: "Republic of the Union of Myanmar Office of the Commander-in-Chief of Defence Services Statement on Stance (30-1- 2021)\n",
    description: '1. The Commander-in-Chief of Defence Services delivered an address in meeting with senior officer trainees from the National Defence College through video conferencing on 27-1-2021, saying that as the Tatmadaw is an armed organization which is of most crucial in defending the State, it is necessary to abide by the Constitution.\n' +
        '2. The information has been released that in his address, the Commander-in- Chief of Defence Services said: "As the Tatmadaw is an armed organization, it needs to abide by the Constitution. So, we all need to follow all the existing laws, not beyond the 2008 Constitution. The Constitution is the mother law for all laws. So, I\'d like to note we all need to abide by the Constitution. If one does not follow the law, such law must be revoked."\n' +
        '3. Depending on the speech, it was found that some organizations and media expressed and wrote the Tatmadaw will revoke the Constitution (2008) as they liked. In fact, the speech of the Commander-in-Chief of Defence Services focused on nature of the Constitution for the senior officer trainees.\n' +
        '4. As the State aimed to practise the single party system (Socialism) in 1962, the 1947 Constitution enacted for the parliamentary democracy was revoked because of impossibilities for continuous practising. Likewise, the 1974 Constitution promulgated for the single part system (Myanmar Socialist Programme Party) was revoked because it could not be practised any more as the State set an aim to practise the multiparty democratic system. With regard to current situation, some 700 delegates from eight strata such as representatives- elect, intellectuals and intelligentsia and ethnic delegates among the people participated in detailed discussions within about seven years and the Constitution was based on outcomes from discussions, and the referendum approved the Constitution to implement the multiparty democratic system the people aspired. The Tatmadaw is also abiding by the Constitution (2008) and doing its tasks within the frame of provisions stipulated in the Constitution. However, some organizations and media defined the speech of the Commander-in-Chief of Defence Services as they liked and issued the statements and new analyses without respecting the full text of the speech.\n' +
        '5. As such, the statement on stance was released that the Tatmadaw will perform its tasks within the frame of enacted law while safeguarding the existing Constitution (2008).\n'
}, {
    title: "Final statement right before the coup!",
    subtitle: "Myanmar Tatmadaw’s Response (31-1-2021)",
    description: 'The Tatmadaw urges some Diplomatic Missions in Myanmar not to make unwarranted assumptions about the situation. The international community should not be endorsing the next steps of the political process on a "business-as-usual" basis, without understanding the actual events, and without any examination of these numbers and lists, which the Tatmadaw laid open to examination by the international and national media on 29 January 2021.\n' +
        'The Tatmadaw is the one pressing for adherence to democratic norms, and requesting the UEC and NLD-led government to make public the official and final data from the UEC. But to date, they have not. The Tatmadaw categorically denies it is impeding Myanmar\'s democratic transition - we would kindly point out that it was the military who set the country on this path of democratic transition since it drew up the 2008 Constitution, which laid out the roadmap for orderly reform and graduate transition to a democracy.\n' +
        'It is not the outcome itself of the elections that the Tatmadaw is objecting to in its interaction with the UEC and the NLD-led government; why then did the government of U Thein Sein, backed by the Tatmadaw, fully accept the 2015 election results that gave the NLD a landslide victory? Rather, the Tatmadaw finds the process of the 2020 election unacceptable, with over 10.5 million cases of potential fraud, such as non-existent voters. Would any of the countries whose Missions issued the Statement accept such massive fraud?\n' +
        'Clearly, some Diplomatic Missions in Myanmar have released a statement without proper knowledge of what has actually happened, and we urge you to reconsider the facts, review the data, and the implications of this statement. The Tatmadaw will do everything possible to adhere to the democratic norms of free and fair elections, as set out by the 2008 Constitution, lasting peace, and inclusive well-being and prosperity for the people of Myanmar.\n',
}]
